import { Resume } from './types';

// Escape a string so it is safe to drop into LaTeX body text.
// Handles the standard reserved characters plus a few common gotchas.
export function tex(input: string | undefined | null): string {
  if (!input) return '';
  let s = String(input);
  // Backslash first, so later replacements don't double-escape.
  s = s.replace(/\\/g, '\\textbackslash{}');
  s = s.replace(/([&%$#_{}])/g, '\\$1');
  s = s.replace(/~/g, '\\textasciitilde{}');
  s = s.replace(/\^/g, '\\textasciicircum{}');
  // Smart quotes -> LaTeX-friendly equivalents.
  s = s.replace(/”|“/g, "''").replace(/‘|’/g, "'");
  return s;
}

// Same as tex() but preserves the LaTeX en-dash / em-dash idioms users
// commonly type into date fields ("2020 -- Present" or "2020 --- 2023").
export function texDates(input: string | undefined | null): string {
  return tex(input);
}

// Build a mailto: / url: link only when value is non-empty.
function urlLink(label: string, href: string, display: string): string {
  if (!display) return '';
  return `\\href{${href}}{\\underline{${tex(display)}}}`;
}

function buildHeading(r: Resume): string {
  const h = r.heading;
  const contactParts: string[] = [];
  if (h.phone) contactParts.push(`\\small ${tex(h.phone)}`);
  if (h.email) contactParts.push(urlLink('email', `mailto:${h.email}`, h.email));
  if (h.linkedin) {
    const href = h.linkedin.startsWith('http') ? h.linkedin : `https://${h.linkedin}`;
    contactParts.push(urlLink('linkedin', href, h.linkedin));
  }
  if (h.github) {
    const href = h.github.startsWith('http') ? h.github : `https://${h.github}`;
    contactParts.push(urlLink('github', href, h.github));
  }
  if (h.website) {
    const href = h.website.startsWith('http') ? h.website : `https://${h.website}`;
    contactParts.push(urlLink('website', href, h.website));
  }

  const contactLine = contactParts.join(' $|$ ');
  const locationLine = h.location ? `\\small ${tex(h.location)} \\\\` : '';

  return `\\begin{center}
    \\textbf{\\Huge \\scshape ${tex(h.name) || '~'}} \\\\ \\vspace{1pt}
    ${locationLine}
    ${contactLine}
\\end{center}`;
}

function buildSummary(r: Resume): string {
  const text = r.heading.summary?.trim();
  if (!text) return '';
  return `\\section{Summary}
  \\small{${tex(text)}}\\vspace{2pt}`;
}

function buildEducation(r: Resume): string {
  if (r.education.length === 0) return '';
  const items = r.education
    .map(
      (e) =>
        `    \\resumeSubheading
      {${tex(e.school)}}{${texDates(e.dates)}}
      {${tex(e.degree)}}{${tex(e.location)}}`
    )
    .join('\n');
  return `\\section{Education}
  \\resumeSubHeadingListStart
${items}
  \\resumeSubHeadingListEnd`;
}

function buildBullets(bullets: string[]): string {
  const valid = bullets.filter((b) => b && b.trim().length > 0);
  if (valid.length === 0) return '';
  const items = valid.map((b) => `        \\resumeItem{${tex(b)}}`).join('\n');
  return `      \\resumeItemListStart
${items}
      \\resumeItemListEnd`;
}

function buildExperience(r: Resume): string {
  if (r.experience.length === 0) return '';
  const items = r.experience
    .map(
      (e) => `    \\resumeSubheading
      {${tex(e.title)}}{${texDates(e.dates)}}
      {${tex(e.company)}}{${tex(e.location)}}
${buildBullets(e.bullets)}`
    )
    .join('\n');
  return `\\section{Experience}
  \\resumeSubHeadingListStart
${items}
  \\resumeSubHeadingListEnd`;
}

function buildProjects(r: Resume): string {
  if (r.projects.length === 0) return '';
  const items = r.projects
    .map((p) => {
      const title =
        `\\textbf{${tex(p.name)}}` +
        (p.tech ? ` $|$ \\emph{${tex(p.tech)}}` : '');
      return `      \\resumeProjectHeading
        {${title}}{${texDates(p.dates)}}
${buildBullets(p.bullets)}`;
    })
    .join('\n');
  return `\\section{Projects}
    \\resumeSubHeadingListStart
${items}
    \\resumeSubHeadingListEnd`;
}

function buildSkills(r: Resume): string {
  if (r.skills.length === 0) return '';
  const lines = r.skills
    .map(
      (s) =>
        `     \\textbf{${tex(s.category)}}{: ${tex(s.items)}} \\\\`
    )
    .join('\n');
  return `\\section{Technical Skills}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
${lines}
    }}
 \\end{itemize}`;
}

function buildHonors(r: Resume): string {
  const valid = r.honors.filter((h) => h.text && h.text.trim().length > 0);
  if (valid.length === 0) return '';
  const items = valid
    .map((h) => `    \\resumeItem{${tex(h.text)}}`)
    .join('\n');
  return `\\section{Honors \\& Awards}
  \\resumeItemListStart
${items}
  \\resumeItemListEnd`;
}

const PREAMBLE = String.raw`%-------------------------
% Resume in Latex
% Based on: https://github.com/sb2nov/resume
% Generated by CV Maker — ATS Friendly
%------------------------

\documentclass[letterpaper,11pt]{article}

\usepackage{latexsym}
\usepackage[empty]{fullpage}
\usepackage{titlesec}
\usepackage{marvosym}
\usepackage[usenames,dvipsnames]{color}
\usepackage{verbatim}
\usepackage{enumitem}
\usepackage[hidelinks]{hyperref}
\usepackage{fancyhdr}
\usepackage[english]{babel}
\usepackage{tabularx}
\input{glyphtounicode}

\pagestyle{fancy}
\fancyhf{}
\fancyfoot{}
\renewcommand{\headrulewidth}{0pt}
\renewcommand{\footrulewidth}{0pt}

\addtolength{\oddsidemargin}{-0.5in}
\addtolength{\evensidemargin}{-0.5in}
\addtolength{\textwidth}{1in}
\addtolength{\topmargin}{-.5in}
\addtolength{\textheight}{1.0in}

\urlstyle{same}

\raggedbottom
\raggedright
\setlength{\tabcolsep}{0in}

\titleformat{\section}{
  \vspace{-4pt}\scshape\raggedright\large
}{}{0em}{}[\color{black}\titlerule \vspace{-5pt}]

\pdfgentounicode=1

\newcommand{\resumeItem}[1]{
  \item\small{
    {#1 \vspace{-2pt}}
  }
}

\newcommand{\resumeSubheading}[4]{
  \vspace{-2pt}\item
    \begin{tabular*}{0.97\textwidth}[t]{l@{\extracolsep{\fill}}r}
      \textbf{#1} & #2 \\
      \textit{\small#3} & \textit{\small #4} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubSubheading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \textit{\small#1} & \textit{\small #2} \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeProjectHeading}[2]{
    \item
    \begin{tabular*}{0.97\textwidth}{l@{\extracolsep{\fill}}r}
      \small#1 & #2 \\
    \end{tabular*}\vspace{-7pt}
}

\newcommand{\resumeSubItem}[1]{\resumeItem{#1}\vspace{-4pt}}

\renewcommand\labelitemii{$\vcenter{\hbox{\tiny$\bullet$}}$}

\newcommand{\resumeSubHeadingListStart}{\begin{itemize}[leftmargin=0.15in, label={}]}
\newcommand{\resumeSubHeadingListEnd}{\end{itemize}}
\newcommand{\resumeItemListStart}{\begin{itemize}}
\newcommand{\resumeItemListEnd}{\end{itemize}\vspace{-5pt}}

`;

export function generateLatex(resume: Resume): string {
  const sections = [
    buildHeading(resume),
    buildSummary(resume),
    buildExperience(resume),
    buildProjects(resume),
    buildEducation(resume),
    buildSkills(resume),
    buildHonors(resume),
  ]
    .filter(Boolean)
    .join('\n\n');

  return `${PREAMBLE}\\begin{document}

${sections}

\\end{document}
`;
}
